services:
  tailscale:
    build: .
    container_name: ts-box
    hostname: warp-coexist
    environment:
      TS_USERSPACE: "true"
      TS_HOSTNAME: "warp-coexist"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_EXTRA_ARGS: "--accept-dns=false"
      TS_SOCKS5_SERVER: ":1055"
    volumes:
      - ts-state:/var/lib/tailscale
      - ts-ssh:/root/.ssh
    ports:
      - "127.0.0.1:5170-5180:5170-5180"
      - "127.0.0.1:8000-8010:8000-8010"
    restart: unless-stopped

volumes:
  ts-state:
  ts-ssh:
